### ISSUE TITLE
[FEATURE] Detect multiple faces

### ISSUE THREAD

**Issue by narayansoni** [narayan954/smartbrain-frontend#10]
### Description

ClarifAi api provides us with a lots of information and within it is an array of detected faces. Currently we just utilize one of those and detect a single face but we can detect multiple faces as well.

**Comment by billy-le** [comment]
Mind if I try to take a crack at this?

**Comment by narayan954** [comment]
> Mind if I try to take a crack at this?

sure go ahead! thanks
