### ISSUE TITLE
If a file with multiple faces is fed to the algo it only detects one face

### ISSUE THREAD

**Issue by vvswps** [narayan954/smartbrain-frontend#22]
### Description

https://images.newscientist.com/wp-content/uploads/2022/02/14174128/PRI_223554170.jpg?crop=4:3,smart&width=1200&height=900&upscale=true

only one face gets highlighted when given the above image

### Steps to reproduce

just paste and submit

### Screenshots

![image](https://user-images.githubusercontent.com/20621664/195689277-24629fbc-8f2e-43ce-aeba-1cd7c4337b09.png)

**Comment by narayan954** [comment]
this one's been resolved in #10
